# Generated by Django 4.2.9 on 2024-02-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppSocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmbarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique='true', verbose_name='Tipos')),
            ],
        ),
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique='true')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('amarre', models.CharField(max_length=5)),
                ('modelo', models.CharField(max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='embarcacion')),
                ('propietario', models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='AppSocios.socios')),
                ('tipo', models.ForeignKey(blank='true', max_length=20, null='true', on_delete=django.db.models.deletion.CASCADE, to='AppEmbarcacion.tipoembarcacion')),
            ],
        ),
    ]
