# Generated by Django 4.2.9 on 2024-02-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, unique='true', verbose_name='Cargos')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dep', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre_mun', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEmpleados.departamento', verbose_name='ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique='true', verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=70, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('sexo', models.CharField(blank='false', choices=[('femenimo', 'Femenino'), ('masculino', 'Masculino')], max_length=12, null='false', verbose_name='Sexo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('fecha_nto', models.DateField()),
                ('inicio_contrato', models.DateField()),
                ('fin_contrato', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleado')),
                ('cargo', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='AppEmpleados.cargos', verbose_name='Cargos')),
                ('ciudad', models.ForeignKey(blank='true', max_length=70, null='true', on_delete=django.db.models.deletion.CASCADE, to='AppEmpleados.municipios', verbose_name='Ciudad')),
                ('departamento', models.ForeignKey(blank='true', max_length=70, null='true', on_delete=django.db.models.deletion.CASCADE, to='AppEmpleados.departamento', verbose_name='Departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
